name: jd-extraction
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11 # You can adjust this based on your Python version
  - pip
  - pip:
      - annotated-types==0.7.0
      - anyio==4.9.0
      - asttokens==3.0.0
      - async-timeout==4.0.3
      - blis==1.3.0
      - catalogue==2.0.10
      - certifi==2025.4.26
      - charset-normalizer==3.4.2
      - click==8.1.8
      - cloudpathlib==0.21.0
      - colorama==0.4.6
      - comm==0.2.2
      - confection==0.1.5
      - cymem==2.0.11
      - debugpy==1.8.14
      - decorator==5.2.1
      - distro==1.9.0
      - et_xmlfile==2.0.0
      - exceptiongroup==1.2.2
      - executing==2.2.0
      - filelock==3.18.0
      - fsspec==2025.3.2
      - greenlet==3.2.1
      - h11==0.16.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==0.30.2
      - idna==3.10
      - ipykernel==6.29.5
      - ipython==8.36.0
      - jedi==0.19.2
      - Jinja2==3.1.6
      - jiter==0.9.0
      - joblib==1.5.0
      - jsonpatch==1.33
      - jsonpointer==3.0.0
      - jupyter_client==8.6.3
      - jupyter_core==5.7.2
      - langchain==0.3.25
      - langchain-core==0.3.58
      - langchain-text-splitters==0.3.8
      - langcodes==3.5.0
      - langsmith==0.3.42
      - language_data==1.3.0
      - marisa-trie==1.2.1
      - markdown-it-py==3.0.0
      - MarkupSafe==3.0.2
      - matplotlib-inline==0.1.7
      - mdurl==0.1.2
      - mpmath==1.3.0
      - murmurhash==1.0.12
      - nest-asyncio==1.6.0
      - networkx==3.4.2
      - numpy==2.2.5
      - openai==1.77.0
      - openpyxl==3.1.5
      - orjson==3.10.18
      - packaging==24.2
      - pandas==2.2.3
      - parso==0.8.4
      - pillow==11.2.1
      - platformdirs==4.3.7
      - preshed==3.0.9
      - prompt_toolkit==3.0.51
      - psutil==7.0.0
      - pure_eval==0.2.3
      - pydantic==2.11.4
      - pydantic_core==2.33.2
      - Pygments==2.19.1
      - PyQt6==6.7.1
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pywin32==310
      - PyYAML==6.0.2
      - pyzmq==26.4.0
      - regex==2024.11.6
      - requests==2.32.3
      - requests-toolbelt==1.0.0
      - rich==14.0.0
      - safetensors==0.5.3
      - scikit-learn==1.6.1
      - scipy==1.15.2
      - sentence-transformers==4.1.0
      - shellingham==1.5.4
      - six==1.17.0
      - smart-open==7.1.0
      - sniffio==1.3.1
      - spacy==3.8.5
      - spacy-legacy==3.0.12
      - spacy-loggers==1.0.5
      - SQLAlchemy==2.0.40
      - srsly==2.5.1
      - stack-data==0.6.3
      - sympy==1.14.0
      - tenacity==9.1.2
      - tokenizers==0.21.1
      - tornado==6.4.2
      - tqdm==4.67.1
      - traitlets==5.14.3
      - transformers==4.51.3
      - typer==0.15.3
      - typing-inspection==0.4.0
      - typing_extensions==4.13.2
      - tzdata==2025.2
      - urllib3==2.4.0
      - wasabi==1.1.3
      - wcwidth==0.2.13
      - weasel==0.4.1
      - webencodings==0.5.1
      - wrapt==1.17.2
      - zstandard==0.23.0
